/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.graphql
 * @generated SignedSource<<f5d74485be824c633987908c92f52938>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type AppContainer_viewer = {|
  +device: ?{|
    +activity: ?$ReadOnlyArray<?{|
      +publisher: ?{|
        +name: ?string;
      |};
      +type: ?"REMOVE_IDP" | "READ_IDP_HISTORY" | "ADD_IDP";
      +createdDate: ?any;
    |}>;
  |};
  +history: ?$ReadOnlyArray<?{|
    +key: ?{|
      +name: ?string;
    |};
    +idp: ?{|
      +id: ?string;
      +name: ?string;
      +type: ?"SAML" | "OAUTH" | "OPEN_ATHENS";
    |};
    +lastActiveDate: ?any;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "AppContainer_viewer",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "DeviceHeader_viewer",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "DeviceType",
      "name": "device",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DeviceAccessType",
          "name": "activity",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "PublisherType",
              "name": "publisher",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                }
              ],
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "type",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "createdDate",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "IdentityProviderUsageType",
      "name": "history",
      "plural": true,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": "key",
          "args": null,
          "concreteType": "IdentityProviderType",
          "name": "idp",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "IdentityProviderType",
          "name": "idp",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "id",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "type",
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "lastActiveDate",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "viewer"
};

module.exports = fragment;
