/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.graphql
 * @generated SignedSource<<e2a55429b222bde5b7713db43f8d4076>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type AppContainer_viewer = {| |};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "AppContainer_viewer",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "DeviceHeader_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "IdpHistory_viewer",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "DeviceActivity_viewer",
      "args": null
    }
  ],
  "type": "viewer"
};

module.exports = fragment;
