/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.graphql
 * @generated SignedSource<<287423bf829a34a8d2dadb3e1a531689>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type AppContainer_viewer = {|
  +history: ?$ReadOnlyArray<?{|
    +key: ?{|
      +name: ?string;
    |};
    +idp: ?{|
      +name: ?string;
      +type: ?"SAML" | "OAUTH" | "OPEN_ATHENS";
    |};
    +lastActiveDate: ?any;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "AppContainer_viewer",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "DeviceHeader_viewer",
      "args": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "IdentityProviderUsageType",
      "name": "history",
      "plural": true,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": "key",
          "args": null,
          "concreteType": "IdentityProviderType",
          "name": "idp",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "IdentityProviderType",
          "name": "idp",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "type",
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "lastActiveDate",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "viewer"
};

module.exports = fragment;
