/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DeviceActivityContainer_viewer.graphql
 * @generated SignedSource<<224866938e40040df0286b00e0a57b1c>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DeviceActivityContainer_viewer = {|
  +device: ?{|
    +activity: ?$ReadOnlyArray<?{|
      +publisher: ?{|
        +name: ?string;
      |};
      +type: ?"REMOVE_IDP" | "READ_IDP_HISTORY" | "ADD_IDP";
      +createdDate: ?any;
    |}>;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DeviceActivityContainer_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "DeviceType",
      "name": "device",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DeviceAccessType",
          "name": "activity",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "PublisherType",
              "name": "publisher",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                }
              ],
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "type",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "createdDate",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "viewer"
};

module.exports = fragment;
