/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DeviceHeaderContainer_viewer.graphql
 * @generated SignedSource<<8a6761282b2b2af900aaf6cbd0301d42>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DeviceHeaderContainer_viewer = {|
  +device: ?{|
    +globalId: ?string;
    +info: ?{|
      +userAgent: ?string;
    |};
  |};
  +latestActivity: ?{|
    +publisher: ?{|
      +name: ?string;
    |};
    +createdDate: ?any;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DeviceHeaderContainer_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "DeviceType",
      "name": "device",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "globalId",
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "DeviceInfoType",
          "name": "info",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "userAgent",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "DeviceAccessType",
      "name": "latestActivity",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PublisherType",
          "name": "publisher",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "name",
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "createdDate",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "viewer"
};

module.exports = fragment;
